exclude:
  - "lib/**"
  - "node_modules/**"
  - "dist/**"

linters:
  StringQuotes:
    enabled: true
    style: double_quotes
  Indentation:
    width: 1
  Comment:
    enabled: false
  LeadingZero:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  SelectorDepth:
    enabled: false
  PropertySortOrder:
    enabled: false
  CapitalizationInSelector:
    enabled: false
  ColorKeyword:
    enabled: false
  BorderZero:
    enabled: false
  NameFormat:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  TrailingSemicolonAfterPropertyValue:
    enabled: false
  UrlFormat:
    enabled: false
  SpaceBeforeBrace:
    enabled: false
  DeclarationOrder:
    enabled: false
  DuplicateProperty:
    enabled: false
  Shorthand:
    enabled: false
  HexFormat:
    enabled: false
  SpaceAfterComma:
    enabled: false
  SpaceAfterPropertyColon:
    enabled: false
  ZeroUnit:
    enabled: false
