language: node_js
node_js:
  - "0.10"
cache: false

install:
  - npm -g install npm@next
  - gem install scss-lint --no-ri --version '=0.24.0'
  - scripts/setup

script:
  - npm run-script travis_script

after_success:
  - npm run-script travis_after_success
