language: node_js
node_js:
  - "0.10"
cache: false

env:
  global:
    - secure: "TdlTg9qHnkCemeB29GqpWjGcnvHbfDprogoD5+jv2bpwLaku76M2JIkYK0KFYscus1jPgDwgQq/WByAATpNUJpqShMgSkj8X1VZTbHhGR9hxSd+jFvzQ38qtMs771SzVXxQPViSU+KVEPmfgk52agNRS73CW9ppyv2wdaWW5ssk=" #Github Token

before_install:
  - sudo apt-get update && sudo apt-get install git

install:
  - scripts/setup

script:
  - grunt && ./scripts/travis_artifacts.sh