language: node_js
node_js:
  - "0.10"
cache: false

env:
  global:
    - secure: "JLds52bUoPVt3sTjZc8NrMusq6P4V8EL5ZUBQJ2BeshmUcisLjvtbI64CYFAhOG2ouX78brtixEjbwsvXr8RQaHZKIfT0xP2IeQAB5DnnERZtGzKkleCp34SSjhfYX/j9i+yvapTlXUW2gyE6F0XYOX5H0QqQ+S33NKvLVx2l0g=" #Github Token

install:
  - scripts/setup

script:
  - grunt && ./scripts/travis_artifacts.sh