language: node_js
node_js:
  - "0.10"
cache: false

env:
  global:
    - secure: "mW/VaQscFpItrkD0nNi/2pR2RpU0bHcXL+P/aNCkJtUXsmuf2btwJcgJUH4o8Jr8+DirnR4brTv2tp0jlk7GKnnR36Rw/iy2LrxwSK6b5eL68g0FYY7in5DGUpEQKzqvTHPGzcQXIwMO85qzKMFWMWjos6EWcO/r8tE7/wSI1hw=" #Github Token

before_install:
  - sudo apt-get update && sudo apt-get install git

install:
  - scripts/setup

script:
  - grunt && ./scripts/travis_artifacts.sh