language: node_js
node_js:
  - "6"
cache: false

sudo: false

before_install:
  - echo "machine github.com login $GH_TOKEN" >> ~/.netrc

install:
  - scripts/setup
  - bundle install

script:
  - npm run-script travis_script

after_success:
  - npm run-script travis_after_success
