#
# Local site settings
remote_theme: wet-boew/gcweb-jekyll
title: "GCWeb, the Canada.ca official theme" # Site name or title
website: "https://wet-boew.github.io/GCWeb/" # URL of your public facing website
global:
  lang: fr
  feedbackPath:
    en: "/sites/feedback/ajax/report-problem-en.html"
    fr: "/sites/feedback/ajax/report-problem-fr.html"
  contextualFooter: # Contextual footer settings
    title:
      fr: "Débuter"
      en: "Get started"
    links: # List of links visible in the contextual footer
      fr:
        - url: "index-fr.html#composantes"
          text: "Composantes"
        - url: "index-fr.html#gabarits"
          text: "Gabarits"
        - url: "index-fr.html#experimentation"
          text: "Méli-mélo et thématiques"
        - url: "index-fr.html#sitesglobal"
          text: "Fonctionnalités globales et de sites"
        - url: "index-fr.html#autre"
          text: "Autre documentation"
        - url: "index-fr.html#implementer-developper"
          text: "Implémenter&nbsp;/ Développer"
      en:
        - url: "index-en.html#components"
          text: "Components"
        - url: "index-en.html#templates"
          text: "Templates"
        - url: "index-en.html#experiment"
          text: "Méli-mélo and thematics"
        - url: "index-en.html#sitesglobal"
          text: "Sites and global functionality"
        - url: "index-en.html#other"
          text: "Other documentation"
        - url: "index-en.html#implementing-developing"
          text: "Implementing&nbsp;/ Developing"

#
# Page front matter defaults
defaults:
  - scope:
      path: "" # Ensure it's applied to all pages
    values:
      layout: default

#
# Collections
collections:
  wetboew-demos:
    output: true
#    permalink: /wet-boew-demos/:name

#
# Jekyll settings
timezone: America/Toronto # Timezone for blog posts and alike
#verbose: true
#quiet: false
sass:
  sass_dir: "sites"
#  load_paths: [
#    "node_modules" # we might only need bootstrap scss
#  ,
#    "node_modules/wet-boew/node_modules" # todo: find a way to include it.
#  ]

#
# Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE*
- SECURITY.md
- Gruntfile.coffee
- CNAME
- "*.tmp"
- Gemfile
- Gemfile.lock
- gcweb-jekyll.gemspec
- .jekyll-cache
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
